apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jonsoku2/kubernetes-practice-1.git' # 깃허브 레포지토리 URL
    targetRevision: HEAD
    path: ./  # app.yaml 파일의 위치
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default'
  syncPolicy:
    automated: {}
