apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - react-deployment.yaml
  - react-service.yaml

commonLabels:
  app: react
  env: production

images:
- name: the2792/react-app
  newTag: new-image-tag
