apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - express-deployment.yaml
  - express-service.yaml

commonLabels:
  app: express
  env: production

images:
- name: the2792/express-app
  newTag: new-image-tag
